FIND_PATH(WIIUSE_INCLUDE_DIR NAMES wiiuse.h
  PATHS
  ${OE_CURRENT_EXTERNALS_DIR}/wiiuse_v0.12/src
  )

IF(WIIUSE_INCLUDE_DIR)
  SET(WIIUSE_FOUND TRUE)
  MARK_AS_ADVANCED(WIIUSE_INCLUDE_DIR)
ENDIF(WIIUSE_INCLUDE_DIR)

IF (WIIUSE_FOUND) 
  INCLUDE_DIRECTORIES(${WIIUSE_INCLUDE_DIR})
ELSE (WIIUSE_FOUND)
  MESSAGE ("WARNING: Could not find wiiuse external source - depending targets will be disabled.")
ENDIF (WIIUSE_FOUND)

